In [1]:
import pandas as pd
import numpy as np
import os
import datetime

In [2]:
#PATH = '../../../../data/dota2/'
PATH = '../../../data/dota2/'

In [3]:
df_train_features = pd.read_csv(os.path.join(PATH, 'train_features.csv.zip'), index_col='match_id_hash')
df_test_features = pd.read_csv(os.path.join(PATH, 'test_features.csv.zip'), index_col='match_id_hash')
df_train_targets = pd.read_csv(os.path.join(PATH, 'train_targets.csv.zip'), index_col='match_id_hash')

df_train_features.shape, df_test_features.shape, df_train_targets.shape

((39675, 245), (10000, 245), (39675, 5))

In [4]:
df_train_features.head()

game_time  game_mode  lobby_type  \
match_id_hash                                                        
a400b8f29dece5f4d266f49f1ae2e98a        155         22           7   
b9c57c450ce74a2af79c9ce96fac144d        658          4           0   
6db558535151ea18ca70a6892197db41         21         23           0   
46a0ddce8f7ed2a8d9bd5edcbb925682        576         22           7   
b1b35ff97723d9b7ade1c9c3cf48f770        453         22           7   

                                  objectives_len  chat_len  r1_hero_id  \
match_id_hash                                                            
a400b8f29dece5f4d266f49f1ae2e98a               1        11          11   
b9c57c450ce74a2af79c9ce96fac144d               3        10          15   
6db558535151ea18ca70a6892197db41               0         0         101   
46a0ddce8f7ed2a8d9bd5edcbb925682               1         4          14   
b1b35ff97723d9b7ade1c9c3cf48f770               1         3          42   

                                  r1_kills  r1_deaths  r1_assists  r1_denies  \
match_id_hash                                                                  
a400b8f29dece5f4d266f49f1ae2e98a         0          0           0          0   
b9c57c450ce74a2af79c9ce96fac144d         7          2           0          7   
6db558535151ea18ca70a6892197db41         0          0           0          0   
46a0ddce8f7ed2a8d9bd5edcbb925682         1          0           3          1   
b1b35ff97723d9b7ade1c9c3cf48f770         0          1           1          0   

                                  ...  d5_stuns  d5_creeps_stacked  \
match_id_hash                     ...                                
a400b8f29dece5f4d266f49f1ae2e98a  ...  0.000000                  0   
b9c57c450ce74a2af79c9ce96fac144d  ...  0.000000                  0   
6db558535151ea18ca70a6892197db41  ...  0.000000                  0   
46a0ddce8f7ed2a8d9bd5edcbb925682  ...  8.664527                  3   
b1b35ff97723d9b7ade1c9c3cf48f770  ...  0.000000                  2   

                                  d5_camps_stacked  d5_rune_pickups  \
match_id_hash                                                         
a400b8f29dece5f4d266f49f1ae2e98a                 0                0   
b9c57c450ce74a2af79c9ce96fac144d                 0                0   
6db558535151ea18ca70a6892197db41                 0                0   
46a0ddce8f7ed2a8d9bd5edcbb925682                 1                3   
b1b35ff97723d9b7ade1c9c3cf48f770                 1                2   

                                  d5_firstblood_claimed  \
match_id_hash                                             
a400b8f29dece5f4d266f49f1ae2e98a                      0   
b9c57c450ce74a2af79c9ce96fac144d                      0   
6db558535151ea18ca70a6892197db41                      0   
46a0ddce8f7ed2a8d9bd5edcbb925682                      0   
b1b35ff97723d9b7ade1c9c3cf48f770                      0   

                                  d5_teamfight_participation  \
match_id_hash                                                  
a400b8f29dece5f4d266f49f1ae2e98a                        0.00   
b9c57c450ce74a2af79c9ce96fac144d                        0.00   
6db558535151ea18ca70a6892197db41                        0.00   
46a0ddce8f7ed2a8d9bd5edcbb925682                        0.00   
b1b35ff97723d9b7ade1c9c3cf48f770                        0.25   

                                  d5_towers_killed  d5_roshans_killed  \
match_id_hash                                                           
a400b8f29dece5f4d266f49f1ae2e98a                 0                  0   
b9c57c450ce74a2af79c9ce96fac144d                 0                  0   
6db558535151ea18ca70a6892197db41                 0                  0   
46a0ddce8f7ed2a8d9bd5edcbb925682                 0                  0   
b1b35ff97723d9b7ade1c9c3cf48f770                 0                  0   

                                  d5_obs_placed  d5_sen_placed  
match_id_hash                     

In [7]:
for feat in df_train_features.columns:
    print(feat)

game_time
game_mode
lobby_type
objectives_len
chat_len
r1_hero_id
r1_kills
r1_deaths
r1_assists
r1_denies
r1_gold
r1_lh
r1_xp
r1_health
r1_max_health
r1_max_mana
r1_level
r1_x
r1_y
r1_stuns
r1_creeps_stacked
r1_camps_stacked
r1_rune_pickups
r1_firstblood_claimed
r1_teamfight_participation
r1_towers_killed
r1_roshans_killed
r1_obs_placed
r1_sen_placed
r2_hero_id
r2_kills
r2_deaths
r2_assists
r2_denies
r2_gold
r2_lh
r2_xp
r2_health
r2_max_health
r2_max_mana
r2_level
r2_x
r2_y
r2_stuns
r2_creeps_stacked
r2_camps_stacked
r2_rune_pickups
r2_firstblood_claimed
r2_teamfight_participation
r2_towers_killed
r2_roshans_killed
r2_obs_placed
r2_sen_placed
r3_hero_id
r3_kills
r3_deaths
r3_assists
r3_denies
r3_gold
r3_lh
r3_xp
r3_health
r3_max_health
r3_max_mana
r3_level
r3_x
r3_y
r3_stuns
r3_creeps_stacked
r3_camps_stacked
r3_rune_pickups
r3_firstblood_claimed
r3_teamfight_participation
r3_towers_killed
r3_roshans_killed
r3_obs_placed
r3_sen_placed
r4_hero_id
r4_kills
r4_deaths
r4_assists
r4_denies


In [5]:
df_train_targets.head()

game_time  radiant_win  duration  \
match_id_hash                                                        
a400b8f29dece5f4d266f49f1ae2e98a        155        False       992   
b9c57c450ce74a2af79c9ce96fac144d        658         True      1154   
6db558535151ea18ca70a6892197db41         21         True      1503   
46a0ddce8f7ed2a8d9bd5edcbb925682        576         True      1952   
b1b35ff97723d9b7ade1c9c3cf48f770        453        False      2001   

                                  time_remaining next_roshan_team  
match_id_hash                                                      
a400b8f29dece5f4d266f49f1ae2e98a             837              NaN  
b9c57c450ce74a2af79c9ce96fac144d             496              NaN  
6db558535151ea18ca70a6892197db41            1482          Radiant  
46a0ddce8f7ed2a8d9bd5edcbb925682            1376              NaN  
b1b35ff97723d9b7ade1c9c3cf48f770            1548              NaN

In [111]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, TimeSeriesSplit
from sklearn.metrics import roc_auc_score, accuracy_score
from sklearn.preprocessing import StandardScaler

In [9]:
X = df_train_features.values
y = df_train_targets['radiant_win'].values

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=17)
len(X_train), len(X_test), y_train.size, y_test.size

(27772, 11903, 27772, 11903)

In [17]:
scaler = StandardScaler()

In [42]:
%%time

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

CPU times: user 255 ms, sys: 76 ms, total: 331 ms
Wall time: 328 ms


#### Без масштабирования результат на тесте очень сильно снижается

In [64]:
%%time
model_sc = LogisticRegression(random_state=17, n_jobs=4)
model_sc.fit(X_train_scaled, y_train)
y_pred = model_sc.predict_proba(X_test_scaled)[:,1]

/home/anton/jupyter_projects/venv/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/anton/jupyter_projects/venv/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))


CPU times: user 3.46 s, sys: 20 ms, total: 3.48 s
Wall time: 3.47 s


In [65]:
roc_auc_score(y_test, y_pred)

0.8117931549829542

In [66]:
accuracy_score(y_test, y_pred > 0.5)

0.7234310677980341

In [40]:
X_valid = df_test_features.values
X_valid_scaled = scaler.transform(X_valid)
y_test_pred = model_sc.predict_proba(X_valid_scaled)[:,1]
df_submission = pd.DataFrame({'radiant_win_prob': y_test_pred}, index=df_test_features.index)

submission_filename = 'submission_{}.csv'.format(datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S'))
df_submission.to_csv(submission_filename)

print('Submission saved to {}'.format(submission_filename))

Submission saved to submission_2019-11-15_15-02-26.csv


In [76]:
from sklearn.linear_model import LassoCV, RidgeClassifierCV

In [116]:
%%time

lasso = LassoCV(cv=5, random_state=17)

lasso.fit(X_train_scaled, y_train)

y_pred_las = lasso.predict(X_test_scaled)

roc_auc_score(y_test, y_pred_las)

CPU times: user 44.8 s, sys: 12.4 s, total: 57.3 s
Wall time: 15.8 s


/home/anton/jupyter_projects/venv/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1455.0870034545699, tolerance: 0.6924848624513894
  positive)


0.8086353963566544

In [118]:
y_pred_las

array([-0.43565368,  0.46950756,  0.44853005, ...,  0.50135051,
        0.45787696,  0.57789449])

In [117]:
X_valid = df_test_features.values
X_valid_scaled = scaler.transform(X_valid)
y_test_pred = lasso.predict_proba(X_valid_scaled)[:,1]
df_submission = pd.DataFrame({'radiant_win_prob': y_test_pred}, index=df_test_features.index)

submission_filename = 'submission_{}.csv'.format(datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S'))
df_submission.to_csv(submission_filename)

print('Submission saved to {}'.format(submission_filename))

AttributeError: 'LassoCV' object has no attribute 'predict_proba'

In [100]:
%%time

ridge = RidgeClassifierCV(cv=10)
ridge.fit(X_train_scaled, y_train)

y_pred_rdg = ridge.predict(X_test_scaled)

roc_auc_score(y_test, y_pred_rdg)

CPU times: user 8.67 s, sys: 3.8 s, total: 12.5 s
Wall time: 3.64 s


0.7193438180743512

In [96]:
def getCoefficients(model, columns):
    """Returns sorted coefficient values of the model"""
    coefs = pd.DataFrame(model.coef_, columns)
    coefs.columns = ["coef"]
    coefs["abs"] = coefs.coef.apply(np.abs)
    return coefs.sort_values(by="abs", ascending=False).drop(["abs"], axis=1)

getCoefficients(lasso, df_train_features.columns)

coef
d5_level         -0.167303
r1_level          0.162635
d4_level         -0.151502
d3_level         -0.148609
r2_level          0.144113
...                    ...
d5_camps_stacked  0.000000
d2_assists       -0.000000
r1_kills          0.000000
d2_sen_placed     0.000000
d1_assists       -0.000000

[245 rows x 1 columns]

In [84]:
lasso.coef_

array([ 2.50745614e-02, -2.01276816e-03,  1.80563030e-03, -1.88526539e-03,
       -2.50471728e-03, -1.43719631e-03,  6.65806834e-03, -6.77375108e-03,
       -1.09466244e-02,  6.62134594e-03,  3.99958854e-02,  0.00000000e+00,
       -5.01199651e-02,  7.44478303e-03,  4.85897637e-03,  4.23568185e-03,
        1.63962012e-01,  5.18740693e-03,  1.01406507e-02,  7.39749402e-03,
        2.96836576e-03,  0.00000000e+00, -0.00000000e+00, -3.45639607e-03,
        1.14520102e-02,  1.09987747e-02, -3.73591768e-03,  2.34599635e-03,
       -4.34910526e-04, -4.54372313e-03,  1.37228326e-02,  6.16953103e-03,
        1.04292335e-02,  1.39498768e-02,  5.93671640e-02,  0.00000000e+00,
       -3.90004089e-02,  7.47066796e-03,  2.78112249e-03, -2.15164501e-03,
        1.43574327e-01,  2.77072752e-03,  7.48216153e-03, -5.02854876e-03,
        8.58137305e-03, -2.86292767e-03,  6.51010535e-03,  3.51478235e-04,
        3.75297673e-03,  7.22322565e-03,  5.77191873e-04,  7.07255432e-03,
        0.00000000e+00, -

In [67]:
from sklearn.ensemble import GradientBoostingClassifier

In [68]:
xgb = GradientBoostingClassifier()

In [69]:
xgb.fit(X_train_scaled, y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [71]:
y_pred_xgb = xgb.predict_proba(X_test_scaled)[:,1]
y_pred_xgb

array([0.02008909, 0.44434299, 0.46210541, ..., 0.41915801, 0.69216327,
       0.59271351])

In [72]:
roc_auc_score(y_test, y_pred_xgb)

0.7816539101751729

In [73]:
accuracy_score(y_test, y_pred_xgb > 0.5)

0.7002436360581366

In [74]:
X_valid = df_test_features.values
X_valid_scaled = scaler.transform(X_valid)
y_test_pred = xgb.predict_proba(X_valid_scaled)[:,1]
df_submission = pd.DataFrame({'radiant_win_prob': y_test_pred}, index=df_test_features.index)

submission_filename = 'submission_{}.csv'.format(datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S'))
df_submission.to_csv(submission_filename)

print('Submission saved to {}'.format(submission_filename))

Submission saved to submission_2019-11-15_15-40-55.csv
